name: TheMind

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN }}
      - uses: actions/checkout@v2
      - name: pull changes
        run: git pull
      - name: run deploy.sh
        run: sh deploy.sh
