name: TheMind

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: pull changes
        run: git pull
      - name: run deploy.sh
        run: sh deploy.sh
